const glosarys = [
    {word: '<em><strong>Ace:</strong></em> Todos los enemigos han muerto, y están esperando su tiempo para renacer. Ideal para empujar las líneas y atacar las Torretas o el Nexo Enemigo.'},
    {word: '<em><strong>ADC:</strong></em> (Attack Damage Carry). Es un campeón tirador que logra hacer el mayor daño en el menor tiempo.'},
    {word: '<em><strong>AoE:</strong></em> Area of Effect (Area de Efecto). Una habilidad que es capaz de golpear un área en lugar de un solo objetivo.'},
    {word: '<em><strong>AP:</strong></em> Ability Power (poder de habilidad). El atributo que mejora la efectividad de algunas habilidades.'},
    {word: '<em><strong>Aura:</strong></em> Una pasiva que no solo afecta al Campeón que la lleva, sino también a Campeones en su rango de trabajo. Una pasiva para compartir.'},
    {word: '<em><strong>BD / Backdoor:</strong></em> Atacar la base enemiga sin esperar a los súbditos de tu equipo. Normalmente se hace cuando los enemigos tardarán en llegar a protegerla. xPeke el AP Carry de Fnatic realiza este procedimiento con frecuencia.'},
    {word: '<em><strong>Bush / Brush:</strong></em> Las hierbas que causan que los campeones que estén dentro no sean vistos por campeones que estén afuera.'},
    {word: '<em><strong>Buff:</strong></em> Normalmente es algo que mejora los atributos de algún campeón.'},
    {word: '<em><strong>Crowd Control (CC):</strong></em> Movimientos que interfieren en los movimientos de otro campeón como aturdimiento, terror, impulsos y cegar.'},
    {word: '<em><strong>Cooldown (CD):</strong></em> En español Enfriamiento. Es el tiempo entre el uso repetido de habilidades.'},
    {word: '<em><strong>Champion (Campeón):</strong></em> El personajes que como invocador, controlas.'},
    {word: '<em><strong>DD:</strong></em> Direct Damage Ability (Habilidad de Daño Directo: Normalmente habilidades que no se pueden esquivar. Por ejemplo: la bola de fuego de Annie.'},
    {word: '<em><strong>Disable:</strong></em> Disable son los hechizos que previenen a los campeones de hacer cualquier acción. Ejemplos son: aturdimiento, root (fijar al suelo).'},
    {word: '<em><strong>DOT:</strong></em> Damage over time (daño por tiempo).'},
    {word: '<em><strong>DPS:</strong></em> Damage Per second (Daño por Segundo). También hace referencia a campeones cuyo principal trabajo es hacer daño (Al contrario que los apoyos y los tanques).'},
    {word: '<em><strong>Executed (Ejecutado):</strong></em> Asesinado por una torreta sin que ningún campeón se lleve la muerte.'},
    {word: '<em><strong>Face-check:</strong></em> Entrar a la hierba (sin otra habilidad u objeto de visión) para verificar la presencia del enemigo o del indicio de un enemigo próximo.'},
    {word: '<em><strong>Farm:</strong></em> Farmear se refiere a conseguir gran cantidad de oro. Como mejor se consigue es matar muchos súbditos muy rápido.'},
    {word: '<em><strong>First blood (FB):</strong></em> Obtener la primera baja del juego'},
    {word: '<em><strong>Feed:</strong></em> Es un término que se utiliza para denominar a alguien que ha muerto demasiadas veces.'},
    {word: '<em><strong>Grass:</strong></em> Ir a mirar la hierba.'},
    {word: '<em><strong>Harass:</strong></em> Molestar al enemigo dañándole poco a poco, forzándole a encerrarse en su torreta o ir de nuevo a la base para curarse.'},
    {word: '<em><strong>Héroe (Hero):</strong></em> Se refiere a los campeones.'},
    {word: '<em><strong>Humiliation (Humillacion):</strong></em> Asesinado por un súbdito sin que ningún campeón se lleve la recompensa.'},
    {word: '<em><strong>IAS:</strong></em> Increased Attack Speed (Velocidad de Ataque Incrementada).'},
    {word: '<em><strong>Juke, juking:</strong></em> Cuando se es perseguido, juking es para atontar a tus enemigos. Normalmente ocurre en la jungla. Un buen juke te libra de tus enemigos explotando su linea de visión, o simplemente hacer que tu enemigo falle al clickearte.'},
    {word: '<em><strong>Jungle (Jg):</strong></em> Atacar a Súbditos neutrales, permitiendo dejar 2 lineas con 1 solo campeón y poder gankear mejor.'},
    {word: '<em><strong>Last Hit (Lh):</strong></em> Dar el último golpe.'},
    {word: '<em><strong>MR:</strong></em> Magic Resist (resistencia mágica). Una protección contra ataques mágicos.'},
    {word: '<em><strong>MS:</strong></em> Movement Speed (velocidad de movimiento).'},
    {word: '<em><strong>Neutrals:</strong></em> Los Súbditos que están en la jungla.'},
    {word: '<em><strong>Neuts:</strong></em> Neutrals.'},
    {word: '<em><strong>Passive (Pasiva):</strong></em> Una habilidad que no se activa pero que ayuda al jugador. Normalmente solo se aplican al jugador que las lleva.'},
    {word: '<em><strong>Proc:</strong></em> Se refiere al arma, objeto o habilidad que se activan con "Posibilidad al golpear" o "Posibilidad de usarse". "Programmed Random Occurence".'},
    {word: '<em><strong>Root:</strong></em> Un efecto negativo que previene que un campeón pueda moverse o usar habilidades.'},
    {word: '<em><strong>Silence (Silencio):</strong></em> Efecto Negativo que previene al campeón de usar habilidades.'},
    {word: '<em><strong>Skillshot:</strong></em> Habilidad que dispara un proyectil que puede ser esquivado. Por ejemplo: El Tiro Místico de Ezreal'},
    {word: '<em><strong>Snowball:</strong></em> Objeto que aumenta su poder con muertes. Por ejemplo: El Roba Almas de Mejai.'},
    {word: '<em><strong>Stun (Aturdimiento):</strong></em> Efecto Negativo que previene al Campeón de usar cualquier acción.'},
    {word: '<em><strong>Summoner (Invocador):</strong></em> Tu representante en el juego. Básicamente eres el titiritero que mueve a los campeones en el juego.'},
    {word: '<em><strong>Support (Apoyo):</strong></em> Campeón que normalmente va a Bot y ayuda al Attack Damage Carry comprándole wards y en general están para ayudar a todo el equipo.'},
    {word: '<em><strong>Tank (Tanque):</strong></em> Campeones que son capaces de resistir muchos golpes y se encargan de iniciar la pelea contra el equipo rival. Tienen mucha vida, armadura / resistencia mágica.'},
    {word: '<em><strong>Torret Hugging, Turret Hug, Thug:</strong></em> Defender la torre permaneciendo bajo ella, básicamente porque no se es capaz de defenderla sin su ayuda.'},
    {word: '<em><strong>TP (Teleport):</strong></em> Hechizo de Invocador que te permite tele-transportarte de un lugar a una torreta, ward o súbdito.'},
    {word: '<em><strong>Ultimate o Ulti:</strong></em> Habilidad definitiva. Se utiliza presionando la tecla R.'},
    {word: '<em><strong>Unique (Única):</strong></em> Algunas pasivas o habilidades son únicas, es decir que no se pueden tener dos.'},
    ]